---
- name: "get Node.js 13"
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: " install node in ec2"
  become: true
  apt: 
    name: ['nodejs']
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
